"""add_webhook_delivery_logs

Revision ID: e76f2f948b6e
Revises: 921e9f0b627b
Create Date: 2026-08-04 11:12:43.351790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76f2f948b6e'
down_revision: Union[str, Sequence[str], None] = '921e9f0b627b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_delivery_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_delivery_logs_id'), 'webhook_delivery_logs', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_delivery_logs_merchant_id'), 'webhook_delivery_logs', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_delivery_logs_merchant_id'), table_name='webhook_delivery_logs')
    op.drop_index(op.f('ix_webhook_delivery_logs_id'), table_name='webhook_delivery_logs')
    op.drop_table('webhook_delivery_logs')
    # ### end Alembic commands ###
